### ISSUE TITLE
config entry issues

### ISSUE THREAD

**Issue by woopstar** [jdeath/BLE-YC01#2]
getting this error:

```
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 202, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
```

Using BLE proxy on an ESP with the following config:

```
esphome:
  name: ble-proxy-1
  friendly_name: ble-proxy-1

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

logger:

api:

ota:
  password: !secret ota_password

web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "ble-proxy-1 Fallback Hotspot"
    password: !secret wifi_fallback_password

captive_portal:

binary_sensor:
  - platform: status
    name: "ESP32 Status"
    
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "ble-proxy-1 IP Address"
    ssid:
      name: "ble-proxy-1 Wi-Fi SSID"
    bssid:
      name: "ble-proxy-1 Wi-Fi BSSID"

  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true

time:
  - platform: sntp
    id: sntp_time
    timezone: !secret ntp_timezone
    servers: !secret ntp_servers

sensor:
  - platform: uptime
    name: "ble-proxy-1 Uptime"

  - platform: wifi_signal
    name: "ble-proxy-1 Wi-Fi Signal"
    update_interval: 60s

switch:
  - platform: restart
    name: "Restart"
    id: switch_restart

# bluetooth proxy
# https://esphome.io/components/bluetooth_proxy.html
esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true
```
